config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Nest expenses under budgets to show their association
  resources :budgets do
    resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  end

  resources :expense_categories, only: [:index, :new, :create, :destroy]
  resources :reports, only: [:index, :show, :new, :create]
  resources :notifications, only: [:index, :update]

  # Root path
  root 'budgets#index'

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  has_many :expenses, dependent: :destroy
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :budget
  belongs_to :category, class_name: 'ExpenseCategory', foreign_key: 'category_id'
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
  has_many :expenses, foreign_key: 'category_id'
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :budgets
  has_many :reports
  has_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  def index
    @budgets = current_user.budgets
  end

  def show
    @budget = Budget.find(params[:id])
    @total = @budget.expenses.sum(:amount)
  end

  def new
    @budget = Budget.new
  end

  def create
    @budget = Budget.new(budget_params)
    @budget.user = current_user
    if @budget.save
      redirect_to @budget, notice: 'Budget created successfully'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @budget.update(budget_params)
      redirect_to @budget, notice: 'Budget updated successfully'
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def set_budget
    @budget = current_user.budgets.find(params[:id])
  end

  def budget_params
    params.require(:budget).permit(:name, :budget_type, :total_amount, :due_date_date)
  end
end

app/controllers/expense_categories_controller.rb
class ExpenseCategoriesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_budget
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  def index
    @expenses = @budget.expenses
  end

  def show

  end

  def new
    @expense = @budget.expenses.new
  end

  def create
    @expense = @budget.expenses.new(expense_params)

    if @expense.save
      redirect_to budget_path(@budget), notice: 'Expense created successfully'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @expense.update(expense_params)
      redirect_to budget_path(@budget), notice: 'Expense updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @expense.destroy
    redirect_to budget_path(@budget), notice: 'Expense deleted successfully'
  end

  private

  def set_budget
    @budget = current_user.budgets.find(params[:budget_id])
  end

  def set_expense
    @expense = @budget.expenses.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, :category_id, :recurrence, :due_date)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
  end

  def update
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/expense_categories_helper.rb
module ExpenseCategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/budgets/create.html.erb
<h1>Budgets#create</h1>
<p>Find me in app/views/budgets/create.html.erb</p>

app/views/budgets/destroy.html.erb
<h1>Budgets#destroy</h1>
<p>Find me in app/views/budgets/destroy.html.erb</p>

app/views/budgets/edit.html.erb
<h1>Budgets#edit</h1>
<p>Find me in app/views/budgets/edit.html.erb</p>

app/views/budgets/index.html.erb
<div class="home-page-container">
  <div class="budget-title">
    <h1>My Budgets</h1>
  </div>

  <% if !@budgets.empty? %>
    <div class="budget-display">
      <% show_budget = @budgets.last %>
      <div class="name">
        <%= link_to show_budget.name, budget_path(show_budget), class: "btn-success" %>
      </div>

      <div class="subcontent">
        <div class="type">
          <%= show_budget.budget_type %>
        </div>

        <div class="amount">
          <%= "R#{show_budget.expenses.sum(:amount)}0" %>
        </div>
      </div>
    </div>

    <div class="budget-buttons">
      <%= link_to "New Budget Plan", new_budget_path, class: "new-budget-button" %>
    </div>

    <div class="budget-container">
      <% @budgets.reverse.each do |budget| %>
        <div class="budget-card">
          <%= link_to budget.name, budget_path(budget), class: "btn-success" %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="budget-buttons">
      <%= link_to "New Budget Plan", new_budget_path, class: "new-budget-button" %>
    </div>

    <div class="budget-display">
      <p>No Budgets Yet.</p>
    </div>
  <% end %>
</div>

app/views/budgets/new.html.erb
<div class="new-page-container">
  <h1 class="new-page-title">New Budget</h1>
  <%= simple_form_for(@budget, html: { class: 'budget-form' }) do |form| %>
    <div class="form-group">
      <%= form.input :name, input_html: { class: 'form-input' } %>
    </div>

    <div class="form-group">
      <%= form.select :budget_type, ['Monthly', 'Yearly', 'Weekly', 'Daily', 'Ad Hoc'], { prompt: 'Select Budget Type' }, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= form.input :due_date, as: :string, input_html: { data: { controller: 'datepicker' }, class: 'form-input' } %>
    </div>

    <div class="form-actions">
      <%= form.submit 'Create Budget', class: 'submit-button' %>
    </div>
  <% end %>

  <%= link_to 'Home', root_path, class: 'regular-button home-button' %>
</div>

app/views/budgets/show.html.erb
<div class="budget-page-container">
  <h1 class="budget-page-title"><%= link_to @budget.name, root_path %></h1>

  <div class="total-amount">
    <div class="total-cost">
      <h2>Total Cost:</h2>
      <h2><%= number_to_currency(@total, unit: "R") %></h2>
    </div>
  </div>

  <hr class="divider">

  <div class="add-expense-button">
    <%= link_to 'Add an Expense', new_budget_expense_path(@budget), class: "regular-button add-expense-btn" %>
  </div>

  <div class="expense-container">
    <% @budget.expenses.each do |expense| %>
      <div class="expense-card">
        <div class="expense-name">
          <%= expense.name %>
        </div>

        <div class="expense-details">
          <div class="left-content">
            <div class="expense-amount">
              <%= number_to_currency(expense.amount, unit: "R") %>
            </div>
            <div class="expense-category">
              <%= expense.category.name if expense.category.present? %>
            </div>
          </div>

          <div class="right-content">
            <%= link_to "Delete",
              budget_expense_path(@budget, expense),
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
              class: "delete-button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/budgets/update.html.erb
<h1>Budgets#update</h1>
<p>Find me in app/views/budgets/update.html.erb</p>

app/views/expense_categories/create.html.erb
<h1>ExpenseCategories#create</h1>
<p>Find me in app/views/expense_categories/create.html.erb</p>

app/views/expense_categories/destroy.html.erb
<h1>ExpenseCategories#destroy</h1>
<p>Find me in app/views/expense_categories/destroy.html.erb</p>

app/views/expense_categories/index.html.erb
<h1>ExpenseCategories#index</h1>
<p>Find me in app/views/expense_categories/index.html.erb</p>

app/views/expense_categories/new.html.erb
<h1>ExpenseCategories#new</h1>
<p>Find me in app/views/expense_categories/new.html.erb</p>

app/views/expenses/create.html.erb
<h1>Expenses#create</h1>
<p>Find me in app/views/expenses/create.html.erb</p>

app/views/expenses/destroy.html.erb
<h1>Expenses#destroy</h1>
<p>Find me in app/views/expenses/destroy.html.erb</p>

app/views/expenses/edit.html.erb
<h1>Expenses#edit</h1>
<p>Find me in app/views/expenses/edit.html.erb</p>

app/views/expenses/index.html.erb
<h1>Expenses#index</h1>
<p>Find me in app/views/expenses/index.html.erb</p>

app/views/expenses/new.html.erb
<div class="new-expense-page-container">
  <h1 class="new-expense-page-title">New Expense</h1>
  <%= simple_form_for [@budget, @expense], html: { class: 'expense-form' } do |form| %>
    <div class="form-group">
      <%= form.input :name, label: "Expense Name", input_html: { class: 'form-input' }, label_html: { class: 'form-label' } %>
    </div>
    <div class="form-group">
      <%= form.input :amount, label: "Amount", input_html: { class: 'form-input', step: "0.01" }, label_html: { class: 'form-label' } %>
    </div>
    <div class="form-group">
      <%= form.input :category_id, collection: ExpenseCategory.all, label: "Category", prompt: "Select a category", input_html: { class: 'form-input' }, label_html: { class: 'form-label' } %>
    </div>
    <div class="form-group">
      <%= form.input :recurrence, label: "Recurrence", as: :select, collection: ['One-time', 'Daily', 'Weekly', 'Monthly', 'Yearly'], prompt: "Select Recurrence", input_html: { class: 'form-input' }, label_html: { class: 'form-label' } %>
    </div>
    <div class="form-actions">
      <%= form.submit "Create Expense", class: "submit-button" %>
    </div>
  <% end %>

  <%= link_to 'Home', root_path, class: "regular-button home-button" %>
</div>

app/views/expenses/show.html.erb
<h1>Expenses#show</h1>
<p>Find me in app/views/expenses/show.html.erb</p>

app/views/expenses/update.html.erb
<h1>Expenses#update</h1>
<p>Find me in app/views/expenses/update.html.erb</p>

app/views/notifications/index.html.erb
<h1>Notifications#index</h1>
<p>Find me in app/views/notifications/index.html.erb</p>

app/views/notifications/update.html.erb
<h1>Notifications#update</h1>
<p>Find me in app/views/notifications/update.html.erb</p>

app/views/reports/create.html.erb
<h1>Reports#create</h1>
<p>Find me in app/views/reports/create.html.erb</p>

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>

app/views/reports/new.html.erb
<h1>Reports#new</h1>
<p>Find me in app/views/reports/new.html.erb</p>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>